"""Export generated office sprites with their 2x2 ground footprint preserved.

Masters and built-in imagegen prompts live beside this script. The export only
crops and resamples true RGBA cutouts; it never paints or regenerates artwork.
"""
import json
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OUTPUT = ROOT / 'graphics/entities/personnel-routing'
PADDING = 4
CONTENT_WIDTH = 144  # 12.5% larger artwork; physical footprint remains 2x2.


def cutout(image):
    assert image.mode == 'RGBA' and image.getchannel('A').getextrema()[0] == 0
    bounds = image.getchannel('A').point(lambda a: 255 if a > 8 else 0).getbbox()
    assert bounds
    x0, y0, x1, y1 = bounds
    return image.crop((max(0, x0 - 2), max(0, y0 - 2), min(image.width, x1 + 2), min(image.height, y1 + 2)))


atlas = Image.open(HERE / 'deployment-master.png').convert('RGBA')
width, height = atlas.size
regions = {'north': (0, 0, width//2, height//2), 'east': (width//2, 0, width, height//2),
           'south': (0, height//2, width//2, height), 'west': (width//2, height//2, width, height)}
sources = {f'input-{direction}': cutout(atlas.crop(box)) for direction, box in regions.items()}
sources['output'] = cutout(Image.open(HERE / 'reception-master.png').convert('RGBA'))
entries = {}
for name, source in sources.items():
    content_height = round(source.height * CONTENT_WIDTH / source.width)
    reduced = source.convert('RGBa').resize((CONTENT_WIDTH, content_height), Image.Resampling.LANCZOS).convert('RGBA')
    sprite = Image.new('RGBA', (CONTENT_WIDTH + 2*PADDING, content_height + 2*PADDING))
    sprite.alpha_composite(reduced, (PADDING, PADDING))
    path = OUTPUT / f'{name}.png'
    sprite.save(path, optimize=True)
    # Bottom of the mechanical base sits on the south edge of the 2x2 tile.
    shift_y = 1 - (sprite.height/2 - PADDING)/64
    entries[name] = {'filename': f'__administratorio__/graphics/entities/personnel-routing/{name}.png',
                     'width': sprite.width, 'height': sprite.height, 'scale': 0.5, 'shift': [0, shift_y]}
    alpha = sprite.getchannel('A')
    assert alpha.getextrema() == (0, 255)
    visible = alpha.getbbox()
    assert visible[0] >= PADDING and visible[1] >= PADDING
    assert visible[2] <= sprite.width-PADDING and visible[3] <= sprite.height-PADDING
    if name in ('input-east', 'output'):
        icon = Image.new('RGBA', (64, 64))
        scale = min(60/source.width, 60/source.height)
        reduced_icon = source.convert('RGBa').resize((round(source.width*scale), round(source.height*scale)), Image.Resampling.LANCZOS).convert('RGBA')
        icon.alpha_composite(reduced_icon, ((64-reduced_icon.width)//2, (64-reduced_icon.height)//2))
        icon.save(OUTPUT / ('input-icon.png' if name.startswith('input') else 'output-icon.png'), optimize=True)

(HERE / 'office-sprites.json').write_text(json.dumps(entries, indent=2) + '\n')
lines = ['-- Generated by Internal/personnel-routing-art/export_offices.py.', 'return {']
for name, entry in entries.items():
    lines.append(f'  ["{name}"] = {{filename="{entry["filename"]}", width={entry["width"]}, height={entry["height"]}, scale=0.5, shift={{0,{entry["shift"][1]}}}}},')
lines.append('}')
(ROOT / 'prototypes/shared/personnel_office_sprites.lua').write_text('\n'.join(lines) + '\n')
print('Exported four deployment directions, fixed reception sprite, and two icons')
