"""Register and export ImageGen shadow masks without repainting their silhouettes.

Reference sheets use 384px cells with the entity origin at (96, 272).
Only atlas splitting, resampling, mask normalization and measured registration
are applied. Original entity artwork is never edited. Factorio applies opacity
with draw_as_shadow; exported nontransparent pixels are pure black.
"""
from pathlib import Path
import json
from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUTPUT = ROOT / 'graphics/entities/personnel-routing'
CELL = 384
ORIGIN = (96, 272)
DIRECTIONS = ('north', 'east', 'south', 'west')
GROUPS = {
    'sign': [f'sign-{d}' for d in DIRECTIONS],
    'multisign': [f'multisign-{d}' for d in DIRECTIONS],
    'deployment': [f'input-{d}' for d in DIRECTIONS],
    'reception': ['output'],
}
# Registration measured against the corresponding reference feet/hub/base.
OFFSETS = {
    'sign-north': (-10, -24), 'sign-east': (-4, -22),
    'sign-south': (-10, 18), 'sign-west': (-7, 18),
    **{f'multisign-{d}': (8, 5) for d in DIRECTIONS},
    **{f'input-{d}': (0, 10 if d == 'west' else 8) for d in DIRECTIONS},
    'output': (0, -14),
}
entries = {}
preview = Image.new('RGBA', (CELL*4, CELL*4), (216, 216, 216, 255))
draw = ImageDraw.Draw(preview)
for row, (group, names) in enumerate(GROUPS.items()):
    master = Image.open(HERE / f'{group}-shadow-master.png').convert('RGBA')
    assert master.getchannel('A').getextrema() == (0, 255), 'Master needs real transparency'
    target = (CELL*2, CELL*2) if len(names) == 4 else (CELL, CELL)
    atlas = master.convert('RGBa').resize(target, Image.Resampling.LANCZOS).convert('RGBA')
    reference = Image.open(HERE / f'reference-{group}.png').convert('RGBA')
    for index, name in enumerate(names):
        x, y = index % 2 * CELL, index // 2 * CELL
        box = (x, y, x+CELL, y+CELL)
        mask = atlas.crop(box).getchannel('A').point(lambda a: a if a > 8 else 0)
        cutout = Image.new('RGBA', (CELL, CELL))
        cutout.putalpha(mask)
        registered = Image.new('RGBA', (CELL, CELL))
        registered.alpha_composite(cutout, OFFSETS[name])
        bounds = registered.getchannel('A').getbbox()
        assert bounds and all((bounds[0] > 0, bounds[1] > 0, bounds[2] < CELL, bounds[3] < CELL)), name+' clips'
        x0, y0, x1, y1 = bounds
        crop = (x0-2, y0-2, x1+2, y1+2)
        sprite = registered.crop(crop)
        filename = name+'-shadow.png'
        sprite.save(OUTPUT / filename, optimize=True)
        entries[name] = {
            'filename': '__administratorio__/graphics/entities/personnel-routing/'+filename,
            'width': sprite.width, 'height': sprite.height, 'scale': 0.5,
            'shift': [(crop[0]+sprite.width/2-ORIGIN[0])/64,
                      (crop[1]+sprite.height/2-ORIGIN[1])/64],
            'draw_as_shadow': True,
        }
        # Registration preview approximates the engine's shadow opacity only.
        sample = registered.copy()
        sample.putalpha(sample.getchannel('A').point(lambda a: round(a*0.5)))
        px, py = index*CELL, row*CELL
        preview.alpha_composite(sample, (px, py))
        preview.alpha_composite(reference.crop(box), (px, py))
        draw.text((px+16, py+16), name, fill=(32, 32, 32, 255))
        assert sprite.getchannel('A').getextrema() == (0, 255)
        assert all(c.getextrema() == (0, 0) for c in sprite.split()[:3])

(HERE / 'sprites.json').write_text(json.dumps(entries, indent=2)+'\n')
lines = ['-- Generated by Internal/personnel-routing-art/shadows/export_shadows.py.',
         '-- Multisign layers inherit the runtime artwork scale in personnel_routing.lua.', 'return {']
for name, e in entries.items():
    lines.append(f'  ["{name}"] = {{filename="{e["filename"]}", width={e["width"]}, height={e["height"]}, scale=0.5, shift={{{e["shift"][0]},{e["shift"][1]}}}, draw_as_shadow=true}},')
lines.append('}')
(ROOT / 'prototypes/shared/personnel_shadow_sprites.lua').write_text('\n'.join(lines)+'\n')
preview.save(HERE / 'registration-preview.png')
print(f'Exported {len(entries)} registered pure-black RGBA shadow layers')
