-- ADMINISTRATORIO: ACHIEVEMENTS
-- Thematic achievements rewarding progression milestones and bureaucratic absurdity.

local icons = "__administratorio__/graphics/icons/"
local icon_layers = require("prototypes.shared.icon_layers")
local building_icons = require("prototypes.shared.building_icons")
local feature_flags = require("feature_flags")

data:extend({
  -------------------------------------------------------------------------------
  -- TIER 0: GETTING STARTED
  -------------------------------------------------------------------------------
  {
    type = "build-entity-achievement",
    name = "welcome-to-the-department",
    to_build = "admin-station",
    icon = icons .. "admin-desk.png",
    icon_size = 64,
    order = "a[getting-started]-a",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "discovery-of-bullshit",
    technology = "discovery-bullshit",
    icon = icons .. "bullshit-ore.png",
    icon_size = 64,
    order = "a[getting-started]-b",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "ink-stained",
    technology = "printing-technology",
    icon = icons .. "ink-cartridge.png",
    icon_size = 64,
    order = "a[getting-started]-c",
    allowed_without_fight = true,
  },

  -------------------------------------------------------------------------------
  -- TIER 1: BUREAUCRACY BEGINS
  -------------------------------------------------------------------------------
  {
    type = "produce-per-hour-achievement",
    name = "form-27b-6-achievement",
    item_product = "form-27b-6",
    amount = 100,
    icon = icons .. "form-27b-6.png",
    icon_size = 64,
    order = "b[bureaucracy-begins]-a",
    allowed_without_fight = true,
  },
  {
    type = "produce-per-hour-achievement",
    name = "paper-pusher",
    item_product = "blank-form",
    amount = 1000,
    icon = icons .. "blank-form.png",
    icon_size = 64,
    order = "b[bureaucracy-begins]-b",
    allowed_without_fight = true,
  },
  {
    type = "use-item-achievement",
    name = "capsule-promise",
    to_use = "promise",
    amount = 1,
    limit_quality = "normal",
    icon = icons .. "bureaucratic-promise.png",
    icon_size = 64,
    order = "b[bureaucracy-begins]-d",
    allowed_without_fight = true,
  },

  -------------------------------------------------------------------------------
  -- TIER 2: MID GAME MILESTONES
  -------------------------------------------------------------------------------
  {
    type = "research-achievement",
    name = "its-a-copy-of-a-copy",
    technology = "local-precedents",
    icon = icons .. "useless-documentation.png",
    icon_size = 64,
    order = "c[mid-game]-a",
    allowed_without_fight = true,
  },
  {
    type = "build-entity-achievement",
    name = "permit-denied",
    to_build = "train-stop",
    amount = 10,
    icon = icons .. "transit-authorization.png",
    icon_size = 64,
    order = "c[mid-game]-b",
    allowed_without_fight = true,
  },
  {
    type = "build-entity-achievement",
    name = "coffee-break",
    to_build = "corporate-breakroom",
    icon = icons .. "corporate-breakroom-v2.png",
    icon_size = 64,
    order = "c[mid-game]-c",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "pneumatic-delivery",
    technology = "pneumatic-form-transport",
    icon = icons .. "blank-form.png",
    icon_size = 64,
    order = "c[mid-game]-d",
    allowed_without_fight = true,
  },

  -------------------------------------------------------------------------------
  -- TIER 3: INDUSTRIAL BUREAUCRACY
  -------------------------------------------------------------------------------
  {
    type = "build-entity-achievement",
    name = "propaganda-machine",
    to_build = "propaganda-distillery",
    icon = "__administratorio__/graphics/entities/propaganda-distillery/base/fuel-refinery-icon.png",
    icon_size = 64,
    order = "d[industrial]-a",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "endless-meetings",
    technology = "board-meetings",
    icon = icons .. "management-written-proposal.png",
    icon_size = 64,
    order = "d[industrial]-b",
    allowed_without_fight = true,
  },
  {
    type = "build-entity-achievement",
    name = "union-strong",
    to_build = "union-headquarters",
    icon = icons .. "government-grant.png",
    icon_size = 64,
    order = "d[industrial]-c",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "environmental-compliance-achievement",
    technology = "environmental-compliance",
    icon = icons .. "environmental-impact-report.png",
    icon_size = 64,
    order = "d[industrial]-d",
    allowed_without_fight = true,
  },

  -------------------------------------------------------------------------------
  -- TIER 4: LATE GAME / MASTERY
  -------------------------------------------------------------------------------
  {
    type = "research-achievement",
    name = "constitutional-scholar",
    technology = "constitutional-law",
    icon = icons .. "regulation.png",
    icon_size = 64,
    order = "e[mastery]-a",
    allowed_without_fight = true,
  },
  {
    type = "research-achievement",
    name = "know-it-all",
    research_all = true,
    icon = icons .. "administrative-science-pack.png",
    icon_size = 256,
    icon_mipmaps = 4,
    order = "e[mastery]-b",
    allowed_without_fight = true,
  },
  {
    type = "use-item-achievement",
    name = "eviction-notice-achievement",
    to_use = "eviction-notice",
    amount = 100,
    limit_quality = "normal",
    icon = icons .. "osha-violation.png",
    icon_size = 64,
    order = "e[mastery]-c",
    allowed_without_fight = true,
  },
  {
    type = "train-path-achievement",
    name = "mass-transit",
    minimum_distance = 2000,
    icon = icons .. "transit-authorization.png",
    icon_size = 64,
    order = "e[mastery]-d",
    allowed_without_fight = true,
  },

  -------------------------------------------------------------------------------
  -- SCRIPTED ACHIEVEMENTS (unlocked via control.lua)
  -------------------------------------------------------------------------------
  {
    type = "achievement",
    name = "first-complaint",
    icon = icons .. "ticket-landscape.png",
    icon_size = 64,
    order = "f[scripted]-a",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "first-protest",
    icon = icons .. "protest-cross.png",
    icon_size = 64,
    order = "f[scripted]-a2",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "case-closed",
    icons = icon_layers.resolved_complaint_icons(icon_layers.ticket_icon("ticket-landscape")),
    icon_size = 64,
    order = "f[scripted]-b",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "protest-suppressed",
    icon = icons .. "basic-excuse.png",
    icon_size = 64,
    order = "f[scripted]-c",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "department-of-everything",
    icon = icons .. "admin-desk.png",
    icon_size = 64,
    order = "f[scripted]-d",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "full-resolution",
    icon = icons .. "taxpayer-money.png",
    icon_size = 64,
    order = "f[scripted]-e",
    allowed_without_fight = true,
  },
  {
    type = "achievement",
    name = "behemoth-paperwork",
    icon = icons .. "filing-l.png",
    icon_size = 64,
    order = "f[scripted]-f",
    allowed_without_fight = true,
  },
})

if feature_flags.space_age_enabled() then
  data:extend({
    -- Space Age Planet Certifications
    {
      type = "research-achievement",
      name = "terms-and-conditions-apply",
      technology = "vulcanus-certification",
      icon = icons .. "management-approval-written.png",
      icon_size = 64,
      order = "g[space-age]-a",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "organically-sourced-nonsense",
      technology = "gleba-conciliation",
      icon = icons .. "bullshit-ore.png",
      icon_size = 64,
      order = "g[space-age]-b",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "file-not-found",
      to_build = "archive-recombination-bureau",
      icons = {
        {icon = "__quality__/graphics/icons/recycler.png", icon_size = 64, tint = {r=0.82, g=0.68, b=0.96, a=1}},
        {icon = icons .. "blank-form.png", icon_size = 64, scale = 0.34, shift = {8, 8}},
      },
      order = "g[space-age]-c",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "frozen-pdf",
      technology = "interplanetary-tube-chromatic",
      icon = icons .. "steel-forge-icon.png",
      icon_size = 64,
      order = "g[space-age]-d",
      allowed_without_fight = true,
    },

    -- Workforce Formation & Orbital Operations
    {
      type = "research-achievement",
      name = "workforce-formation-achievement",
      technology = "worker-formation",
      icon = icons .. "formation-center.png",
      icon_size = 64,
      order = "h[orbital]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "administrative-space-station-achievement",
      to_build = "administrative-space-station",
      icon = icons .. "space-age/administrative-space-station.png",
      icon_size = 64,
      order = "h[orbital]-b",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "orbital-employment-catapult-achievement",
      to_build = "orbital-employment-catapult",
      icon = icons .. "asteroid-processing-docket.png",
      icon_size = 64,
      order = "h[orbital]-c",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "trajectory-compliance-array-achievement",
      to_build = "trajectory-compliance-array",
      icons = building_icons.trajectory_array("junior"),
      order = "h[orbital]-d",
      allowed_without_fight = true,
    },

    -- Chromatic Printing
    {
      type = "research-achievement",
      name = "chromatic-printing-achievement",
      technology = "chromatic-printing",
      icon = icons .. "space-age/chromatic-printer.png",
      icon_size = 64,
      order = "i[chromatic]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "chromatic-printer-achievement",
      to_build = "chromatic-printer",
      icon = icons .. "steel-forge-icon.png",
      icon_size = 64,
      order = "i[chromatic]-b",
      allowed_without_fight = true,
    },
    {
      type = "produce-per-hour-achievement",
      name = "triple-ink-threat",
      item_product = "trichromatic-permit",
      amount = 100,
      icon = icons .. "trichromatic-permit.png",
      icon_size = 64,
      order = "i[chromatic]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "ink-hoarder",
      item_product = "ink",
      amount = 10000,
      limited_to_one_game = false,
      icon = icons .. "ink-cartridge.png",
      icon_size = 64,
      order = "i[chromatic]-d",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "cyan-magenta-yellow-black",
      item_product = "composite-chroma-ribbon",
      amount = 1000,
      limited_to_one_game = false,
      icon = icons .. "ink-cartridge.png",
      icon_size = 64,
      order = "i[chromatic]-e",
      allowed_without_fight = true,
    },

    -- Vulcanus Certification
    {
      type = "build-entity-achievement",
      name = "notary-public",
      to_build = "notary-office",
      icon = icons .. "space-age/notary-office.png",
      icon_size = 64,
      order = "j[vulcanus]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "territorial-arbitrator",
      to_build = "territorial-arbitration-post",
      icon = icons .. "space-age/territorial-arbitration-post.png",
      icon_size = 64,
      order = "j[vulcanus]-b",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "demolisher-eviction-specialist",
      item_product = "territorial-deed",
      amount = 5,
      limited_to_one_game = false,
      icon = icons .. "territorial-deed.png",
      icon_size = 64,
      order = "j[vulcanus]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "chartered-accountant",
      item_product = "offworld-metallurgy-charter",
      amount = 100,
      limited_to_one_game = false,
      icon = icons .. "offworld-metallurgy-charter.png",
      icon_size = 64,
      order = "j[vulcanus]-d",
      allowed_without_fight = true,
    },

    -- Gleba Conciliation
    {
      type = "build-entity-achievement",
      name = "conciliation-officer-achievement",
      to_build = "conciliation-desk",
      icon = icons .. "space-age/conciliation-desk.png",
      icon_size = 64,
      order = "k[gleba]-a",
      allowed_without_fight = true,
    },
    {
    type = "build-entity-achievement",
    name = "capture-bureau-achievement",
    to_build = "capture-bureau",
    icons = {
      {icon = icons .. "admin-desk.png", icon_size = 64},
      {icon = "__base__/graphics/icons/small-biter.png", icon_size = 64, scale = 0.35, shift = {8, 8}},
    },
      order = "k[gleba]-b",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "space-tourism-mogul",
      item_product = "public-transportation-contract",
      amount = 500,
      limited_to_one_game = false,
      icon = icons .. "public-transportation-contract.png",
      icon_size = 64,
      order = "k[gleba]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-per-hour-achievement",
      name = "symbiosis-specialist",
      item_product = "symbiosis-record",
      amount = 100,
      icon = icons .. "symbiosis-record.png",
      icon_size = 64,
      order = "k[gleba]-d",
      allowed_without_fight = true,
    },

    -- Fulgora Digital Services
    {
      type = "build-entity-achievement",
      name = "digital-services-bureau-achievement",
      to_build = "digital-services-bureau",
      icon = icons .. "space-age/digital-services-bureau.png",
      icon_size = 64,
      order = "l[fulgora]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "archive-recombinator",
      to_build = "archive-recombination-bureau",
      icon = icons .. "useless-documentation.png",
      icon_size = 64,
      order = "l[fulgora]-b",
      allowed_without_fight = true,
    },
    {
    type = "produce-achievement",
    name = "form-gambler",
    item_product = "old-archive",
    amount = 1000,
    limited_to_one_game = false,
    icon = icons .. "useless-documentation.png",
      icon_size = 64,
      order = "l[fulgora]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "relay-clerk-corps",
      item_product = "relay-clerk",
      amount = 10,
      limited_to_one_game = false,
      icon = icons .. "data.png",
      icon_size = 64,
      order = "l[fulgora]-d",
      allowed_without_fight = true,
    },

    -- Interplanetary Tube Network
    {
      type = "build-entity-achievement",
      name = "tube-terminus",
      to_build = "interplanetary-terminus",
      icon = icons .. "space-age/interplanetary-terminus.png",
      icon_size = 64,
      order = "m[aquilo]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "laser-printer-achievement",
      to_build = "laser-printer",
      icon = icons .. "space-age/laser-printer.png",
      icon_size = 64,
      order = "m[aquilo]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "thermal-paper-pusher",
      item_product = "thermal-transfer-sheet",
      amount = 5000,
      limited_to_one_game = false,
      icon = icons .. "blank-form.png",
      icon_size = 64,
      order = "m[aquilo]-d",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "ribbon-collector",
      item_product = "composite-chroma-ribbon",
      amount = 2000,
      limited_to_one_game = false,
      icon = icons .. "ink-cartridge.png",
      icon_size = 64,
      order = "m[aquilo]-e",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "interplanetary-correspondent",
      item_product = "unified-operations-charter",
      amount = 50,
      limited_to_one_game = false,
      icon = icons .. "unified-operations-charter.png",
      icon_size = 64,
      order = "m[aquilo]-f",
      allowed_without_fight = true,
    },

    -- Cross-Planet Bureaucracy
    {
      type = "produce-achievement",
      name = "cyan-yellow-bureaucrat",
      item_product = "cyan-yellow-form",
      amount = 500,
      limited_to_one_game = false,
      icon = icons .. "cyan-yellow-form.png",
      icon_size = 64,
      order = "n[cross-planet]-a",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "cyan-magenta-bureaucrat",
      item_product = "cyan-magenta-form",
      amount = 500,
      limited_to_one_game = false,
      icon = icons .. "cyan-magenta-form.png",
      icon_size = 64,
      order = "n[cross-planet]-b",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "yellow-magenta-bureaucrat",
      item_product = "yellow-magenta-form",
      amount = 500,
      limited_to_one_game = false,
      icon = icons .. "yellow-magenta-form.png",
      icon_size = 64,
      order = "n[cross-planet]-c",
      allowed_without_fight = true,
    },
    {
      type = "produce-achievement",
      name = "hardened-data-hoarder",
      item_product = "hardened-data-vault",
      amount = 100,
      limited_to_one_game = false,
      icon = icons .. "hardened-data-vault.png",
      icon_size = 64,
      order = "n[cross-planet]-d",
      allowed_without_fight = true,
    },

    -- Bureaucratic Transcendence
    {
      type = "research-achievement",
      name = "bureaucratic-transcendence-achievement",
      technology = "bureaucratic-transcendence",
      icons = building_icons.public_train_stop(),
      order = "o[transcendence]-a",
      allowed_without_fight = true,
    },
    {
      type = "build-entity-achievement",
      name = "form-free-transit",
      to_build = "public-train-stop",
      amount = 50,
      icon = "__base__/graphics/icons/train-stop.png",
      icon_size = 64,
      order = "o[transcendence]-b",
      allowed_without_fight = true,
    },

    -- Orbital Upgrades
    {
      type = "research-achievement",
      name = "maxed-out-orbital-capacity",
      technology = "orbital-employment-capacity-4",
      icon = icons .. "asteroid-processing-docket.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-a",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "maxed-out-orbital-damage",
      technology = "orbital-employment-damage-5",
      icon = icons .. "asteroid-processing-docket.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-b",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "speed-demon-arrays",
      technology = "trajectory-compliance-speed-9",
      icon = icons .. "management-approval-written.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-c",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "executive-jurisdiction",
      technology = "trajectory-compliance-jurisdiction-3",
      icon = icons .. "management-approval-written.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-d",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "chromatic-trunk",
      technology = "interplanetary-tube-chromatic",
      icon = icons .. "ink-cartridge.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-e",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "vulcanus-export-licensed",
      technology = "vulcanus-export-charters",
      icon = icons .. "industrial-charter.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-g",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "cyan-yellow-merged",
      technology = "cyan-yellow-bureaucracy",
      icon = icons .. "cyan-yellow-form.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-h",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "cyan-magenta-merged",
      technology = "cyan-magenta-bureaucracy",
      icon = icons .. "cyan-magenta-form.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-i",
      allowed_without_fight = true,
    },
    {
      type = "research-achievement",
      name = "yellow-magenta-merged",
      technology = "yellow-magenta-bureaucracy",
      icon = icons .. "yellow-magenta-form.png",
      icon_size = 64,
      order = "p[orbital-upgrades]-j",
      allowed_without_fight = true,
    },
  })
end
