local function bulk_copy_recipe(name, recipe)
  recipe.name = name
  recipe.localised_name = {"recipe-name." .. name}
  return recipe
end

data:extend({
  -- Greenhouse & Coffee
  { type = "recipe", name = "greenhouse-wood",      category = "admin-greenhouse", enabled = false, ingredients = {{type="fluid", name="water", amount=100}},                                                                      results = {{type="item", name="wood", amount=10}},                                                  energy_required = 30 },
  {
    type = "recipe", name = "greenhouse-discovery", category = "admin-greenhouse", enabled = false,
    icon = "__administratorio__/graphics/icons/coffee-bean.png", icon_size = 32,
    subgroup = "admin-raw", order = "c0",
    ingredients = {{type="item", name="wood", amount=10}, {type="fluid", name="water", amount=50}},
    results = {
      {type="item", name="coffee-bean", amount=1, probability=0.1},
      {type="item", name="wood", amount=5}
    },
    main_product = "coffee-bean",
    energy_required = 10
  },
  { type = "recipe", name = "coffee-plantation",      category = "admin-greenhouse",   enabled = false, ingredients = {{type="item", name="coffee-bean", amount=1}, {type="fluid", name="water", amount=100}}, results = {{type="item", name="coffee-bean", amount=3}},  energy_required = 45 },
  { type = "recipe", name = "coffee-refining",        category = "watercooler-gossip",    enabled = false, subgroup = "admin-raw", order = "c1", ingredients = {{type="item", name="coffee-bean", amount=1}, {type="fluid", name="water", amount=50}}, results = {{type="fluid", name="liquid-coffee", amount=50}}, energy_required = 3 },

  -- Batch Smelting (Stone Furnace - requires carbon offset certificate)
  { type = "recipe", name = "iron-plate-batch",   category = "smelting-basic", enabled = true,  ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="iron-ore", amount=10}},    results = {{type="item", name="iron-plate", amount=10}},   energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "copper-plate-batch", category = "smelting-basic", enabled = true,  ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="copper-ore", amount=10}},  results = {{type="item", name="copper-plate", amount=10}}, energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "steel-plate-batch",  category = "smelting-basic", enabled = false, ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="iron-plate", amount=25}},  results = {{type="item", name="steel-plate", amount=5}},  energy_required = 90, allow_decomposition = false },
  { type = "recipe", name = "stone-brick-batch",  category = "smelting-basic", enabled = true,  ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="stone", amount=20}},       results = {{type="item", name="stone-brick", amount=10}},  energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "dubious-data-batch", category = "smelting-basic", enabled = true,  ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="bullshit-ore", amount=10}}, results = {{type="item", name="dubious-data", amount=10}}, energy_required = 32,  allow_decomposition = false },

  -- Printing / Copy Recipes
  bulk_copy_recipe("copy-blank-form", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-form.png",       icon_size = 64, ingredients = {{type="item", name="blank-form", amount=1},                    {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-form", amount=6}}, main_product = "blank-form",                    energy_required = 5 }),
  bulk_copy_recipe("copy-blank-approval", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-approval.png",   icon_size = 64, ingredients = {{type="item", name="blank-approval", amount=1},                {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-approval", amount=6}},                main_product = "blank-approval",                energy_required = 5 }),
  bulk_copy_recipe("copy-blank-directive", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-directive.png",  icon_size = 64, ingredients = {{type="item", name="blank-directive", amount=1},               {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-directive", amount=6}},               main_product = "blank-directive",               energy_required = 5 }),
  bulk_copy_recipe("copy-carbon-offset-certificate", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/carbon-offset-certificate-basic.png",  icon_size = 64, ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1},{type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="carbon-offset-certificate-basic", amount=6}}, main_product = "carbon-offset-certificate-basic", energy_required = 5 }),
  bulk_copy_recipe("copy-form-27b-6", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-form.png",       icon_size = 64, ingredients = {{type="item", name="form-27b-6", amount=1},                   {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="form-27b-6", amount=6}},                   main_product = "form-27b-6",                   energy_required = 5 }),
  bulk_copy_recipe("copy-environmental-impact-report", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/crappy-report.png",    icon_size = 64, ingredients = {{type="item", name="environmental-impact-report", amount=1},   {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="environmental-impact-report", amount=6}},   main_product = "environmental-impact-report",   energy_required = 8 }),
  bulk_copy_recipe("copy-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/work-order.png", icon_size = 64, ingredients = {{type="item", name="work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="work-order", amount=6}}, main_product = "work-order", energy_required = 5 }),
  bulk_copy_recipe("copy-safety-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/safety-work-order.png", icon_size = 64, ingredients = {{type="item", name="safety-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="safety-work-order", amount=6}}, main_product = "safety-work-order", energy_required = 5 }),
  bulk_copy_recipe("copy-construction-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/construction-work-order.png", icon_size = 64, ingredients = {{type="item", name="construction-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="construction-work-order", amount=6}}, main_product = "construction-work-order", energy_required = 5 }),
  bulk_copy_recipe("copy-management-verbal-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/management-verbal-work-order.png", icon_size = 64, ingredients = {{type="item", name="management-verbal-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="management-verbal-work-order", amount=6}}, main_product = "management-verbal-work-order", energy_required = 5 }),
  bulk_copy_recipe("copy-management-written-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/management-written-work-order.png", icon_size = 64, ingredients = {{type="item", name="management-written-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="management-written-work-order", amount=6}}, main_product = "management-written-work-order", energy_required = 8 }),
  bulk_copy_recipe("copy-research-grant-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/research-grant-work-order.png", icon_size = 64, ingredients = {{type="item", name="research-grant-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="research-grant-work-order", amount=6}}, main_product = "research-grant-work-order", energy_required = 5 }),
  bulk_copy_recipe("copy-chemical-handling-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/chemical-handling-work-order.png", icon_size = 64, ingredients = {{type="item", name="chemical-handling-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="chemical-handling-work-order", amount=6}}, main_product = "chemical-handling-work-order", energy_required = 8 }),
  bulk_copy_recipe("copy-radiological-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/radiological-work-order.png", icon_size = 64, ingredients = {{type="item", name="radiological-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="radiological-work-order", amount=6}}, main_product = "radiological-work-order", energy_required = 8 }),

  -- Compacted Rubble (T0 derivative — industrially compressed rubble)
  { type = "recipe", name = "compacted-rubble-production", category = "smelting-basic", enabled = false, ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="redundant-rubble", amount=5}}, results = {{type="item", name="compacted-rubble", amount=5}}, energy_required = 16 },

  -- Charcoal Production (T3 — batch-burn wood into coal)
  { type = "recipe", name = "charcoal-production", category = "smelting-basic", enabled = false, ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="wood", amount=25}}, results = {{type="item", name="coal", amount=5}}, energy_required = 40, allow_decomposition = false },

})
