local function bulk_copy_recipe(name, recipe)
  recipe.name = name
  recipe.localised_name = {"recipe-name." .. name}
  return recipe
end

data:extend({
  -- Greenhouse & Coffee -> admin-raw
  { type = "recipe", name = "greenhouse-wood",      category = "admin-greenhouse", enabled = false, subgroup = "admin-raw", order = "a-a", ingredients = {{type="fluid", name="water", amount=100}},                                                                      results = {{type="item", name="wood", amount=12}},                                                  energy_required = 24 },
  {
    type = "recipe", name = "greenhouse-discovery", category = "admin-greenhouse", enabled = false,
    icon = "__administratorio__/graphics/icons/coffee-bean.png", icon_size = 32,
    subgroup = "admin-raw", order = "a-b",
    ingredients = {{type="item", name="wood", amount=10}, {type="fluid", name="water", amount=50}},
    results = {
      {type="item", name="coffee-bean", amount=1, probability=0.1},
      {type="item", name="wood", amount=5}
    },
    main_product = "coffee-bean",
    energy_required = 10
  },
  { type = "recipe", name = "coffee-plantation",      category = "admin-greenhouse",   enabled = false, subgroup = "admin-raw", order = "a-c", ingredients = {{type="item", name="coffee-bean", amount=1}, {type="fluid", name="water", amount=100}}, results = {{type="item", name="coffee-bean", amount=5}},  energy_required = 30 },
  { type = "recipe", name = "coffee-refining",        category = "watercooler-gossip",    enabled = false, subgroup = "admin-raw", order = "a-d", ingredients = {{type="item", name="coffee-bean", amount=1}, {type="fluid", name="water", amount=50}}, results = {{type="fluid", name="liquid-coffee", amount=50}}, energy_required = 3 },

  -- Batch Smelting (Stone Furnace): alternate recipes for vanilla intermediates,
  -- so they stay in the vanilla Intermediate Products tab -> admin-intermediate
  { type = "recipe", name = "iron-plate-batch",   category = "smelting-basic", enabled = true,  subgroup = "admin-intermediate", order = "a", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="iron-ore", amount=10}},    results = {{type="item", name="iron-plate", amount=10}},   energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "copper-plate-batch", category = "smelting-basic", enabled = true,  subgroup = "admin-intermediate", order = "b", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="copper-ore", amount=10}},  results = {{type="item", name="copper-plate", amount=10}}, energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "steel-plate-batch",  category = "smelting-basic", enabled = false, subgroup = "admin-intermediate", order = "c", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="iron-plate", amount=25}},  results = {{type="item", name="steel-plate", amount=5}},  energy_required = 90, allow_decomposition = false },
  { type = "recipe", name = "stone-brick-batch",  category = "smelting-basic", enabled = true,  subgroup = "admin-intermediate", order = "d", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="stone", amount=20}},       results = {{type="item", name="stone-brick", amount=10}},  energy_required = 32,  allow_decomposition = false },
  { type = "recipe", name = "dubious-data-batch", category = "smelting-basic", enabled = true,  subgroup = "admin-data-economy", order = "c-e", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="bullshit-ore", amount=10}}, results = {{type="item", name="dubious-data", amount=10}}, energy_required = 32,  allow_decomposition = false },

  -- Printing / Copy Recipes -> admin-printed-forms
  bulk_copy_recipe("copy-blank-form", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-form.png",       icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-a", ingredients = {{type="item", name="blank-form", amount=1},                    {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-form", amount=6}}, main_product = "blank-form",                    energy_required = 15 }),
  bulk_copy_recipe("copy-blank-approval", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-approval.png",   icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-b", ingredients = {{type="item", name="blank-approval", amount=1},                {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-approval", amount=6}},                main_product = "blank-approval",                energy_required = 15 }),
  bulk_copy_recipe("copy-blank-directive", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/blank-directive.png",  icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-c", ingredients = {{type="item", name="blank-directive", amount=1},               {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="blank-directive", amount=6}},               main_product = "blank-directive",               energy_required = 15 }),
  bulk_copy_recipe("copy-carbon-offset-certificate", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/carbon-offset-certificate-basic.png",  icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-d", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1},{type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="carbon-offset-certificate-basic", amount=6}}, main_product = "carbon-offset-certificate-basic", energy_required = 15 }),
  bulk_copy_recipe("copy-form-27b-6", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/form-27b-6.png",         icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-e", ingredients = {{type="item", name="form-27b-6", amount=1},                   {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="form-27b-6", amount=6}},                   main_product = "form-27b-6",                   energy_required = 15 }),
  bulk_copy_recipe("copy-environmental-impact-report", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/crappy-report.png",    icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-f", ingredients = {{type="item", name="environmental-impact-report", amount=1},   {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="advanced-circuit", amount=1}}, results = {{type="item", name="environmental-impact-report", amount=6}},   main_product = "environmental-impact-report",   energy_required = 20 }),
  bulk_copy_recipe("copy-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-g", ingredients = {{type="item", name="work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="work-order", amount=6}}, main_product = "work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-safety-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/safety-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-h", ingredients = {{type="item", name="safety-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="safety-work-order", amount=6}}, main_product = "safety-work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-construction-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/construction-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-i", ingredients = {{type="item", name="construction-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="construction-work-order", amount=6}}, main_product = "construction-work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-management-verbal-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/management-verbal-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-j", ingredients = {{type="item", name="management-verbal-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="management-verbal-work-order", amount=6}}, main_product = "management-verbal-work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-management-written-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/management-written-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-k", ingredients = {{type="item", name="management-written-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="management-written-work-order", amount=6}}, main_product = "management-written-work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-research-grant-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/research-grant-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-l", ingredients = {{type="item", name="research-grant-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="research-grant-work-order", amount=6}}, main_product = "research-grant-work-order", energy_required = 20 }),
  bulk_copy_recipe("copy-chemical-handling-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/chemical-handling-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-m", ingredients = {{type="item", name="chemical-handling-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="chemical-handling-work-order", amount=6}}, main_product = "chemical-handling-work-order", energy_required = 25 }),
  bulk_copy_recipe("copy-radiological-work-order", { type = "recipe", category = "printing-advanced", enabled = false, icon = "__administratorio__/graphics/icons/radiological-work-order.png", icon_size = 64, subgroup = "admin-printed-forms", order = "g-c-n", ingredients = {{type="item", name="radiological-work-order", amount=1}, {type="item", name="paper", amount=5}, {type="item", name="ink", amount=1}, {type="item", name="processing-unit", amount=1}}, results = {{type="item", name="radiological-work-order", amount=6}}, main_product = "radiological-work-order", energy_required = 25 }),

  -- Compacted Rubble -> admin-data-economy
  {
    type = "recipe",
    name = "compacted-rubble-electric",
    category = "smelting",
    enabled = false,
    subgroup = "admin-data-economy", order = "c-a",
    ingredients = {{type="item", name="redundant-rubble", amount=1}},
    results = {{type="item", name="compacted-rubble", amount=1}},
    energy_required = 3.2,
    allow_decomposition = false,
    hidden_in_factoriopedia = true,
  },
  { type = "recipe", name = "compacted-rubble-production", category = "smelting-basic", enabled = false, subgroup = "admin-data-economy", order = "c-b", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="redundant-rubble", amount=5}}, results = {{type="item", name="compacted-rubble", amount=5}}, energy_required = 16 },

  -- Charcoal Production: alternate recipe for vanilla coal -> admin-intermediate
  { type = "recipe", name = "charcoal-production", category = "smelting-basic", enabled = false, subgroup = "admin-intermediate", order = "e", ingredients = {{type="item", name="carbon-offset-certificate-basic", amount=1}, {type="item", name="wood", amount=30}}, results = {{type="item", name="coal", amount=8}}, energy_required = 30, allow_decomposition = false },

})
