data:extend({
  -- Filing Stage
  { type = "recipe", name = "filing-landscape",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-landscape", amount=1},    {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-l", amount=1}}, energy_required = 5 },
  { type = "recipe", name = "filing-smog",         category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-smog", amount=1},         {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-s", amount=1}}, energy_required = 10 },
  { type = "recipe", name = "filing-noise",        category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-noise", amount=1},        {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-n", amount=1}}, energy_required = 15 },
  { type = "recipe", name = "filing-unemployment", category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-unemployment", amount=1}, {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-u", amount=1}}, energy_required = 20 },

  -- Case Stage
  { type = "recipe", name = "case-smog",         category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-s", amount=1}, {type="item", name="paper", amount=10},                          {type="item", name="redundant-rubble", amount=2}},              results = {{type="item", name="case-s", amount=1}}, energy_required = 15 },
  { type = "recipe", name = "case-noise",        category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-n", amount=1}, {type="item", name="data", amount=10},                           {type="item", name="carbon-offset-certificate-verified", amount=1}, {type="item", name="refined-nonsense", amount=2}}, results = {{type="item", name="case-n", amount=1}}, energy_required = 30 },
  { type = "recipe", name = "case-unemployment", category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-u", amount=1}, {type="item", name="data", amount=1},                            {type="item", name="government-grant", amount=1}, {type="fluid", name="liquid-coffee", amount=25}},              results = {{type="item", name="case-u", amount=1}}, energy_required = 45 },

  -- Brief Stage
  { type = "recipe", name = "brief-noise",        category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-n", amount=1}, {type="item", name="white-paper", amount=1}, {type="item", name="policy", amount=1}},                     results = {{type="item", name="brief-n", amount=1}}, energy_required = 60 },
  { type = "recipe", name = "brief-unemployment", category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-u", amount=1}, {type="item", name="regulation", amount=1},  {type="item", name="treasury-bond", amount=1}, {type="item", name="refined-nonsense", amount=3}},                results = {{type="item", name="brief-u", amount=1}}, energy_required = 90 },

  -- Final Resolution
  { type = "recipe", name = "landscape-final",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-l", amount=1}, {type="item", name="basic-excuse", amount=1}},                                                                                                      results = {{type="item", name="resolved-landscape", amount=1}},    energy_required = 5 },
  { type = "recipe", name = "smog-final",         category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-s", amount=1},   {type="fluid", name="misinformation", amount=50},  {type="fluid", name="liquid-coffee", amount=50}},                                                    results = {{type="item", name="resolved-smog", amount=1}},         energy_required = 20 },
  { type = "recipe", name = "noise-final",        category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="brief-n", amount=1},  {type="item", name="policy", amount=10},           {type="fluid", name="liquid-coffee", amount=250}, {type="item", name="narrative", amount=2}, {type="item", name="credentials", amount=2}}, results = {{type="item", name="resolved-noise", amount=1}},        energy_required = 90 },
  { type = "recipe", name = "unemployment-final", category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="brief-u", amount=1},  {type="item", name="regulation", amount=20},       {type="fluid", name="liquid-coffee", amount=500}, {type="item", name="narrative", amount=3}, {type="item", name="credentials", amount=3}}, results = {{type="item", name="resolved-unemployment", amount=1}}, energy_required = 180 },

  -- ===== SPITTER COMPLAINT PIPELINE =====

  -- Filing Stage (Spitter)
  { type = "recipe", name = "filing-littering",   category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-littering", amount=1},  {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-lt", amount=1}}, energy_required = 5 },
  { type = "recipe", name = "filing-hazmat",      category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-hazmat", amount=1},     {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-h", amount=1}}, energy_required = 10 },
  { type = "recipe", name = "filing-loitering",   category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-loitering", amount=1},  {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-lo", amount=1}}, energy_required = 15 },
  { type = "recipe", name = "filing-vagrancy",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="ticket-vagrancy", amount=1},   {type="item", name="blank-form", amount=1}}, results = {{type="item", name="filing-v", amount=1}}, energy_required = 20 },

  -- Case Stage (Spitter)
  { type = "recipe", name = "case-hazmat",        category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-h", amount=1},  {type="item", name="paper", amount=8},  {type="item", name="compacted-rubble", amount=2}},                                                        results = {{type="item", name="case-h", amount=1}},  energy_required = 15 },
  { type = "recipe", name = "case-loitering",     category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-lo", amount=1}, {type="item", name="data", amount=8},   {type="item", name="credentials", amount=1}, {type="item", name="refined-nonsense", amount=2}},             results = {{type="item", name="case-lo", amount=1}}, energy_required = 30 },
  { type = "recipe", name = "case-vagrancy",      category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-v", amount=1},  {type="item", name="data", amount=1},   {type="item", name="policy", amount=1}, {type="fluid", name="liquid-coffee", amount=25}},                                                                   results = {{type="item", name="case-v", amount=1}},  energy_required = 45 },

  -- Brief Stage (Spitter)
  { type = "recipe", name = "brief-loitering",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-lo", amount=1}, {type="item", name="white-paper", amount=1}, {type="item", name="regulation", amount=1}},                                                              results = {{type="item", name="brief-lo", amount=1}}, energy_required = 60 },
  { type = "recipe", name = "brief-vagrancy",     category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-v", amount=1},  {type="item", name="policy", amount=1},      {type="item", name="treasury-bond", amount=1}, {type="item", name="refined-nonsense", amount=3}},            results = {{type="item", name="brief-v", amount=1}},  energy_required = 90 },

  -- Final Resolution (Spitter)
  { type = "recipe", name = "littering-final",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="filing-lt", amount=1}, {type="item", name="crappy-report", amount=1}},                                                                                                       results = {{type="item", name="resolved-littering", amount=1}},  energy_required = 7 },
  { type = "recipe", name = "hazmat-final",       category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="case-h", amount=1},   {type="fluid", name="misinformation", amount=40}, {type="fluid", name="liquid-coffee", amount=60}},                                                      results = {{type="item", name="resolved-hazmat", amount=1}},     energy_required = 20 },
  { type = "recipe", name = "loitering-final",    category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="brief-lo", amount=1}, {type="item", name="regulation", amount=8},    {type="fluid", name="liquid-coffee", amount=200}, {type="item", name="narrative", amount=2}, {type="item", name="credentials", amount=2}}, results = {{type="item", name="resolved-loitering", amount=1}},  energy_required = 90 },
  { type = "recipe", name = "vagrancy-final",     category = "bureaucracy-resolution", enabled = false, ingredients = {{type="item", name="brief-v", amount=1},  {type="item", name="policy", amount=15},        {type="fluid", name="liquid-coffee", amount=400}, {type="item", name="narrative", amount=3}, {type="item", name="credentials", amount=3}}, results = {{type="item", name="resolved-vagrancy", amount=1}},   energy_required = 180 },
})
